# Generated by Django 3.1.5 on 2021-02-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0008_auto_20210201_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ala_Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.TextField()),
                ('ala', models.TextField()),
                ('situacao', models.TextField(blank=True, null=True)),
                ('cor', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ala', 'leito'],
            },
        ),
        migrations.AlterModelOptions(
            name='internacao_paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='internacao_paciente',
            name='ala',
        ),
        migrations.RemoveField(
            model_name='internacao_paciente',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='internacao_paciente',
            name='leito',
        ),
        migrations.RemoveField(
            model_name='internacao_paciente',
            name='situacao',
        ),
        migrations.AddField(
            model_name='internacao_paciente',
            name='ala_leito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internacao.ala_leito'),
        ),
    ]
