# Generated by Django 3.1.6 on 2021-02-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0009_auto_20210201_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
