# Generated by Django 3.1.6 on 2021-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0010_auto_20210203_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacao_paciente',
            name='alta',
            field=models.DateTimeField(null=True),
        ),
    ]
