# Generated by Django 3.1.6 on 2021-02-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0011_auto_20210205_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
