# Generated by Django 3.1.6 on 2021-02-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0012_paciente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletim_medico_paciente',
            old_name='previsao_alta',
            new_name='pressao_arterial_med',
        ),
    ]
