# Generated by Django 3.1.6 on 2021-02-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacao', '0013_auto_20210208_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim_medico_paciente',
            name='previsao_alta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
